#define QMTIK_I 4
#define QMTIK_H 16
#define QMTIK_L 8
#define QMTIK_O 3
#define QMTIK_A_SCALE 0.50f
#define QMTIK_W_SCALE 0.08f
#define QMTIK_LEAKY_RELU_ACTV
#define QMTIK_SOFT_MAX_PP
#define QMTIK_CROSS_ENTROPY_COST

#define QMTIK_EPOCHS 64

#define QMTIK_BETA1 0.9f
#define QMTIK_BETA2 0.999f
#define QMTIK_EPS 1e-8f
#define QMTIK_TRAINING_SAMPLES 120
#define QMTIK_TESTING_SAMPLES 30

#define QMTIK_BATCH_SIZE 32
#define QMTIK_INIT_ALPHA 0.001f
#define QMTIK_LR_NO_DECAY

#define QMTIK_COLLECT_REPORT_DATA
