#define QMTIK_I 784
#define QMTIK_H 256
#define QMTIK_L 2
#define QMTIK_O 10
#define QMTIK_A_SCALE 0.25f
#define QMTIK_W_SCALE 0.02f
#define QMTIK_LEAKY_RELU_ACTV
#define QMTIK_SOFT_MAX_PP
#define QMTIK_ARGMAX_COST

#define QMTIK_INIT_ALPHA 0.001f
#define QMTIK_LR_NO_DECAY

#define QMTIK_L2_LAMBDA 0.0f
#define QMTIK_GRADIENT_CLIP 1e13f
#define QMTIK_PRUNE_THRESHOLD 0.0f

#define QMTIK_BETA1 0.9f
#define QMTIK_BETA2 0.999f
#define QMTIK_EPS 1e-8f