#define QMTIK_I 784
#define QMTIK_H 256
#define QMTIK_L 2
#define QMTIK_O 10
#define QMTIK_LEAKY_RELU_ACTV
#define QMTIK_SOFT_MAX_PP
#define QMTIK_CROSS_ENTROPY_COST
#define QMTIK_ALPHA 0.001f
#define QMTIK_EPOCHS 8
#define QMTIK_W_SCALE 0.05f
#define QMTIK_A_SCALE 0.5f
#define QMTIK_BETA1 0.9f
#define QMTIK_BETA2 0.999f
#define QMTIK_EPS 1e-8f
#define QMTIK_EPOCHS_DEBUG_UPDATE_POINT 1
#define QMTIK_SAMPLE_NUMBER_DEBUG_UPDATE_POINT 1024
#define QMTIK_TRAIN_DEBUG
#define QMTIK_TEST_BEFORE_QUANT_DEBUG
#define QMTIK_TEST_AFTER_QUANT_DEBUG
